version: "3.7"
services:
  web:
    image: go-clean-arch
    container_name: article_management_api
    ports:
      - 9090:9090
    depends_on:
      # mysql:
      #   condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./config.json:/app/config.json

  mysql:
    image: mysql:8.3
    container_name: go_clean_arch_mysql
    command: mysqld --user=root
    volumes:
      - ./article.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=article
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  postgres:
    image: postgres:latest
    container_name: ecommerce_go_postgres
    restart: always
    volumes:
      - ./sql/article-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=article
      - POSTGRES_USER=nhatnguyen
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

